from pathlib import Path
import re
import sys

root = Path(__file__).resolve().parents[1]

required_files = [
    "START_HERE.md",
    "AGENTS.md",
    "HARC_MANIFEST.yaml",
    "HARC_CONTEXT_INTERFACE.yaml",
    "CONTRIBUTING.md",
    "core/CONTENT_CORE.md",
    "core/FORM_CORE.md",
    "core/DECISION_LOG.md",
    "docs/working-memory/current-focus.md",
    "docs/working-memory/task-plan.md",
    "docs/working-memory/work-log.md",
    "evidence/source-policy.md",
    "_quarto.yml",
    "index.qmd",
    "references.qmd",
    "references.bib",
    "book.css",
    "scripts/check_quarto_source.py",
    ".github/workflows/publish-book.yml",
    "project.yaml",
    "website.yaml",
    "project-stack.yaml",
    "project-stack.lock.yaml",
    "scripts/check_stack_consistency.py",
]

forbidden_paths = [
    "main.tex",
    "bookstyle.tex",
    "chapters",
    "epub.css",
    "web-manuscript",
    "web-assets",
    "scripts/build_web_source.py",
    "scripts/migrate_to_quarto.py",
    ".github/workflows/quarto-first.yml",
    "因果推理深度读本.pdf",
]

errors = []

for rel in required_files:
    if not (root / rel).is_file():
        errors.append(f"missing required project file: {rel}")

for rel in forbidden_paths:
    if (root / rel).exists():
        errors.append(f"forbidden legacy path remains: {rel}")

quarto_path = root / "_quarto.yml"
configured = []
if quarto_path.is_file():
    quarto_text = quarto_path.read_text(encoding="utf-8")
    configured = re.findall(
        r"(?m)^\s*-\s+(manuscript/[^\s#]+\.qmd)\s*$", quarto_text
    )

actual = sorted(
    p.relative_to(root).as_posix()
    for p in (root / "manuscript").glob("*.qmd")
)
configured_set = set(configured)
actual_set = set(actual)

if len(configured) != 17:
    errors.append(f"_quarto.yml must list exactly 17 manuscript QMD files; found {len(configured)}")
if configured_set != actual_set:
    missing_from_config = sorted(actual_set - configured_set)
    missing_from_disk = sorted(configured_set - actual_set)
    if missing_from_config:
        errors.append("manuscript QMD not listed in _quarto.yml: " + ", ".join(missing_from_config))
    if missing_from_disk:
        errors.append("configured manuscript QMD missing from disk: " + ", ".join(missing_from_disk))

legacy_markers = [
    "Generated from canonical LaTeX",
    "Do not edit this file directly",
    "web-assets/",
    "\\begin{tikzpicture}",
]
for rel in actual:
    text = (root / rel).read_text(encoding="utf-8")
    for marker in legacy_markers:
        if marker in text:
            errors.append(f"legacy marker in canonical QMD: {rel}: {marker}")

makefile = root / "Makefile"
if makefile.is_file():
    make_text = makefile.read_text(encoding="utf-8")
    for marker in ("main.tex", "chapters/", "latexmk", "xelatex", "TinyTeX", "dvisvgm"):
        if marker in make_text:
            errors.append(f"legacy build marker in Makefile: {marker}")

manifest = root / "HARC_MANIFEST.yaml"
if manifest.is_file():
    manifest_text = manifest.read_text(encoding="utf-8")
    for required in (
        'body: "manuscript/*.qmd"',
        'bibliography: "references.bib"',
        'book_structure: "_quarto.yml"',
        'mode: "project-adapted-harc-lite"',
    ):
        if required not in manifest_text:
            errors.append(f"manifest invariant missing: {required}")

if errors:
    print("Project governance validation failed:", file=sys.stderr)
    for error in errors:
        print(f"- {error}", file=sys.stderr)
    raise SystemExit(1)

print(f"Validated project governance and {len(actual)} canonical manuscript files.")
