from pathlib import Path
import re
import sys

root = Path(__file__).resolve().parents[1]
manuscript = root / "manuscript"
quarto = (root / "_quarto.yml").read_text(encoding="utf-8")

configured = re.findall(
    r"(?m)^\s*-\s+(manuscript/[^\s#]+\.qmd)\s*$",
    quarto,
)
actual = sorted(
    p.relative_to(root).as_posix()
    for p in manuscript.glob("*.qmd")
)

errors = []

if len(configured) != 17:
    errors.append(f"_quarto.yml must list exactly 17 manuscript QMD files; found {len(configured)}")

configured_set = set(configured)
actual_set = set(actual)
for rel in sorted(configured_set - actual_set):
    errors.append(f"configured manuscript file missing: {rel}")
for rel in sorted(actual_set - configured_set):
    errors.append(f"canonical manuscript file not listed in _quarto.yml: {rel}")

files = [root / rel for rel in configured if (root / rel).is_file()]
text = "\n".join(p.read_text(encoding="utf-8") for p in files)

placeholder = re.compile(
    r"(?mi)^\s*(?:TODO|TBD|FIXME|待补|待写|占位)(?:\s*[:：-].*)?\s*$"
)
for match in placeholder.finditer(text):
    errors.append(f"placeholder line remains: {match.group(0).strip()}")

for pattern in (
    r"\\chapter\{",
    r"\\section\{",
    r"\\subsection\{",
    r"\\textcite\{",
    r"\\parencite\{",
    r"\\begin\{document\}",
    r"WEBTABLE\d+",
    r"WEBTIKZ\d+",
    r"web-assets/",
    r"Generated from canonical LaTeX",
    r"Do not edit this file directly",
):
    if re.search(pattern, text):
        errors.append(f"legacy migration markup remains: {pattern}")

bib = (root / "references.bib").read_text(encoding="utf-8")
bibkeys = set(re.findall(r"@[A-Za-z]+\s*\{\s*([^,\s]+)", bib))

# Validate unambiguous Pandoc bracket citations only. Bare @tokens can be ordinary
# handles/usernames in prose or code; Quarto/Pandoc remains responsible for
# interpreting narrative citations during the full render.
citation_groups = re.findall(r"\[[^\]\n]*@[^\]\n]+\]", text)
cited = {
    key
    for group in citation_groups
    for key in re.findall(r"(?<![\w@])@([A-Za-z0-9_:.+-]+)", group)
}
missing_keys = sorted(key for key in cited if key not in bibkeys)
if missing_keys:
    errors.append("missing bibliography keys: " + ", ".join(missing_keys[:30]))

asset_refs = set(re.findall(r"\.\./assets/([^\s\"')>]+)", text))
for rel in sorted(asset_refs):
    if not (root / "assets" / rel).exists():
        errors.append(f"missing asset: assets/{rel}")

if errors:
    print("Quarto source validation failed:", file=sys.stderr)
    for error in errors:
        print(f"- {error}", file=sys.stderr)
    raise SystemExit(1)

print(
    f"Validated {len(files)} manuscript files from _quarto.yml "
    f"and {len(cited)} bracket citation keys."
)
